# Generated by Django 5.2.8 on 2025-12-02 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=20, unique=True)),
                ('lesson1_completed', models.BooleanField(default=False)),
                ('lesson2_completed', models.BooleanField(default=False)),
                ('lesson3_completed', models.BooleanField(default=False)),
                ('lesson4_completed', models.BooleanField(default=False)),
                ('lesson5_completed', models.BooleanField(default=False)),
                ('lesson6_completed', models.BooleanField(default=False)),
                ('lesson7_completed', models.BooleanField(default=False)),
                ('lesson8_completed', models.BooleanField(default=False)),
                ('lesson9_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
