# Generated by Django 5.2.7 on 2025-12-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_lessonquizmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsubmission',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
