# Generated by Django 5.2.7 on 2025-12-05 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizsubmission_num_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit1',
            unique_together={('user', 'unit_code')},
        ),
        migrations.AlterField(
            model_name='unit1',
            name='unit_code',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson1_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson2_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson3_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson4_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson5_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson6_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson7_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson8_completed',
        ),
        migrations.RemoveField(
            model_name='unit1',
            name='lesson9_completed',
        ),
    ]
