# Generated by Django 5.2.7 on 2025-12-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_unit1_unique_together_alter_unit1_unit_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit1',
            name='lesson1_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson2_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson3_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson4_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson5_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson6_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson7_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson8_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit1',
            name='lesson9_completed',
            field=models.BooleanField(default=False),
        ),
    ]
